name: Mon Workflow qui tâche
run-name: J'suis en train de faire des trucs
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependances
        run: npm ci

      - name: Lancer mes tests
        run: npm test

      - name: Dire "C'est gagné!"
        run: echo "C'est gagné"
