name: Mon Workflow qui tâche
run-name: J'suis en train de faire des trucs
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Récup le code de mon repo
        uses: actions/checkout@v3

      - name: Install dependances
        run: npm ci

      - name: Lancer mes tests
        run: npm test

      - name: Dire "C'est gagné!"
        run: echo "C'est gagné"

      - name: Build pour la prod
        run: npm run build

      - name: Deployer vers Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "./dist"
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
